### ISSUE TITLE
correct __add__ and __sub__ exception handling

### ISSUE THREAD

**Issue by chukinas** [kstark/months#2]
both `__add__` and `__sub__`: 
The `ValueError` should be replaced with a `TypeError`, since we're handling the wrong type of variable.

`__sub__` only: 
Currently error message ``Only ints can be added to months``. This should be changed to `Only ints can be subtracted from months`.

**Comment by kstark** [comment]
Should be addressed in [1.1.0](https://pypi.org/project/months/1.1.0/)
